/*
 * WARNING: There is nothing in this file for students to edit or change.
 *          This file is intended to have no student-serviceable code.
 *
 * "Draw" your GUI using the "Design" tab, and remember to give
 * them memorable variable names in the "Properties" panel
 * as well as make them public variables.
 * 
 * For convenience, you may want to set the default visibility of 
 * GUI elements to be public by going to:
 *    The NetBeans Preferences or Settings menu -> Miscellaneous -> GUI Builder
 * Then set Variables Modifier to public.
 */
package cs20viewcontroller;

import cs20models.AllModelsForView;

/**
 * WARNING: Do NOT modify or write any code in this file!
 *
 * @author cheng
 */
public class DrawnView extends AllModelsForView {
    // WARNING: Do NOT modify or write any code in this file!
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    public DrawnView() {
        initComponents();
    }// </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playStopBtn = new javax.swing.JToggleButton();
        pauseUnpause = new javax.swing.JToggleButton();
        speedSlider = new javax.swing.JSlider();
        wolvesCheck = new javax.swing.JCheckBox();
        rabbitKillBtn = new javax.swing.JButton();
        wolvesKillBtn = new javax.swing.JButton();
        grassKillBtn = new javax.swing.JButton();
        evolutionCheckBox = new javax.swing.JCheckBox();
        speedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playStopBtn.setText("Play");
        playStopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playStopBtnActionPerformed(evt);
            }
        });

        pauseUnpause.setText("Pause");
        pauseUnpause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseUnpauseActionPerformed(evt);
            }
        });

        speedSlider.setMajorTickSpacing(10);
        speedSlider.setMaximum(240);
        speedSlider.setMinimum(20);
        speedSlider.setMinorTickSpacing(1);
        speedSlider.setValue(60);

        wolvesCheck.setSelected(true);
        wolvesCheck.setText("Wolves On/Off");
        wolvesCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wolvesCheckActionPerformed(evt);
            }
        });

        rabbitKillBtn.setText("Rabbit Disease");

        wolvesKillBtn.setText("Wolves Disease");

        grassKillBtn.setText("Grass Disease");
        grassKillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grassKillBtnActionPerformed(evt);
            }
        });

        evolutionCheckBox.setText("Evolution");
        evolutionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evolutionCheckBoxActionPerformed(evt);
            }
        });

        speedLabel.setText("Speed");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(507, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(speedLabel)
                                    .add(51, 51, 51))
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, speedSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(pauseUnpause, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(rabbitKillBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(wolvesKillBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(grassKillBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(layout.createSequentialGroup()
                                            .add(12, 12, 12)
                                            .add(wolvesCheck))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(evolutionCheckBox)
                                            .add(23, 23, 23))))))
                        .add(12, 12, 12))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(playStopBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(playStopBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pauseUnpause, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(speedLabel)
                .add(3, 3, 3)
                .add(speedSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rabbitKillBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(wolvesKillBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(grassKillBtn)
                .add(4, 4, 4)
                .add(wolvesCheck)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(evolutionCheckBox)
                .addContainerGap(504, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playStopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playStopBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playStopBtnActionPerformed

    private void wolvesCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wolvesCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wolvesCheckActionPerformed

    private void pauseUnpauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseUnpauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pauseUnpauseActionPerformed

    private void grassKillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grassKillBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grassKillBtnActionPerformed

    private void evolutionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evolutionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evolutionCheckBoxActionPerformed
    // WARNING: Do NOT modify or write any code in this file!
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox evolutionCheckBox;
    public javax.swing.JButton grassKillBtn;
    public javax.swing.JToggleButton pauseUnpause;
    public javax.swing.JToggleButton playStopBtn;
    public javax.swing.JButton rabbitKillBtn;
    public javax.swing.JLabel speedLabel;
    public javax.swing.JSlider speedSlider;
    public javax.swing.JCheckBox wolvesCheck;
    public javax.swing.JButton wolvesKillBtn;
    // End of variables declaration//GEN-END:variables
}
